version: "2.2"
services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iris
    ports:
      - 52773:52773
      - 51773:51773
    volumes:
      - ./test:/test
