version: "2.2"
services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iris
    ports:
      - 51883:1972
      - 52883:52773
      - 53883:53773
    volumes:
      - ./test:/test
      - ./Practice:/Practice
