version: "2.2"
services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iris
    ports:
      - 1972:1972
      - 52773:52773
    volumes:
      - ./test:/test
      - ./Practice:/Practice
