services:

  # InterSystems IRIS 
  iris:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iris
    ports:
      - 1972:1972
      - 52773:52773
    volumes:
      - ./test:/test
      - ./Practice:/Practice
      - ./install:/install

  # Sample Angular Web Application that uses InterSystems IRIS
  webapp:
    build:
      context: sample-webapp
      dockerfile: Dockerfile
      args:
        NG_BUILD_OPTS: build:production
    container_name: webapp
    ports:
    - "8080:80"

  # Sample external database to integrate from InterSystems IRIS interoperability framework  
  mysql:
    build:
      context: mysql
      dockerfile: Dockerfile
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3306:3306"